# Generated by Django 2.2.5 on 2020-03-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
