# Generated by Django 2.2.5 on 2020-03-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='cluster',
            field=models.IntegerField(default=0),
        ),
    ]
